include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
  
  errors:
    todo: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_constructors_in_immutables: ignore
    use_key_in_widget_constructors: ignore
    avoid_print: ignore
    unused_import: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    
  exclude:
    - build/**
    - android/**
    - ios/**
    - .dart_tool/**

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    avoid_print: false
    unnecessary_const: false
    unnecessary_new: false